const allLoveWords = [
    { word: "Devotion", message: "Devotion is the quiet promise of forever, whispered in every glance and touch." },
    { word: "Passion", message: "'Passion is the fire that ignites the soul and burns away the shadows of doubt.' — The Cruel Prince, Holly Black" },
    { word: "Tenderness", message: "Tenderness is the gentle touch that heals the heart and soothes the soul." },
    { word: "Adoration", message: "Adoration is the silent song of the heart, sung only for the one who holds it." },
    { word: "Romance", message: "'Romance is the art of turning ordinary moments into something magical.' — The Star-Touched Queen, Roshani Chokshi" },
    { word: "Affection", message: "Affection is the warmth that wraps around you like a comforting embrace." },
    { word: "Intimacy", message: "'Intimacy is not just about closeness, but about sharing the deepest parts of yourself.' — The Night Circus, Erin Morgenstern" },
    { word: "Desire", message: "'Desire is the spark that lights the flame of love.' — A Court of Thorns and Roses, Sarah J. Maas" },
    { word: "Comfort", message: "Comfort is the quiet assurance that you are loved, just as you are." },
    { word: "Trust", message: "'Trust is the glue of life. It's the most essential ingredient in effective communication.' — Stephen Covey" },
    { word: "Longing", message: "'Longing is the ache that reminds us of what we hold dear.' — The Song of Achilles, Madeline Miller" },
    { word: "Joy", message: "Joy is the light that dances in your eyes when you see the one you love." },
    { word: "Hope", message: "'Hope is the anchor that keeps love steady in the storm.' — The Fault in Our Stars, John Green" },
    { word: "Serenity", message: "Serenity is the peace that comes from knowing you are loved unconditionally." },
    { word: "Belonging", message: "'Belonging is the feeling of finally finding where you are meant to be.' — The Raven Boys, Maggie Stiefvater" },
    { word: "Cherish", message: "To cherish is to hold someone so dear that their happiness becomes your own." },
    { word: "Spirit", message: "Tomorrow is a new day. Wake up and start it with a new spirit." },
    { word: "Enchantment", message: "'Enchantment is the magic woven into every moment spent with the one you love.' — Uprooted, Naomi Novik" },
    { word: "Whisper", message: "'A whisper of love can be louder than the noisiest crowd.' — The Cruel Prince, Holly Black" },
    { word: "Promise", message: "A promise is the thread that ties hearts together through time and distance." },
    { word: "Dream", message: "'Dreams are the seeds of love, waiting to bloom in the garden of reality.' — The Night Circus, Erin Morgenstern" },
    { word: "Heartbeat", message: "A heartbeat in sync with another is the purest rhythm of love." },
    { word: "Surrender", message: "'To surrender to love is to find strength in vulnerability.' — A Court of Mist and Fury, Sarah J. Maas" },
    { word: "Eternity", message: "'Eternity is not about time, but about the moments that last forever in the heart.' — The Time Traveler's Wife, Audrey Niffenegger" },
    { word: "Sacrifice", message: "Sacrifice is the silent language of love, spoken in actions rather than words." },
    { word: "Fidelity", message: "'Fidelity is the quiet vow that echoes in every choice made for love.' — The Bronze Horseman, Paullina Simons" },
    { word: "Passionate", message: "'Passionate love is the fire that warms even the coldest of hearts.' — Wuthering Heights, Emily Brontë" },
    { word: "Tender", message: "Tenderness is the gentle hand that wipes away tears and soothes the soul." },
    { word: "Devoted", message: "'To be devoted is to find your purpose in the happiness of another.' — Jane Eyre, Charlotte Brontë" },
    { word: "Enamored", message: "To be enamored is to see the world through the colors of love." },
    { word: "Yearning", message: "'Yearning is the heart's way of calling out to what it loves.' — The Song of Achilles, Madeline Miller" },
    { word: "Rapture", message: "Rapture is the breathless moment when love feels like flying." },
    { word: "Admire", message: "'To admire is to see the beauty in someone that the world may overlook.' — Pride and Prejudice, Jane Austen" },
    { word: "Caring", message: "Caring is the quiet strength that holds love together through every storm." },
    { word: "Endearment", message: "'Endearment is the sweet language of love, spoken in every little gesture.' — Little Women, Louisa May Alcott" },
    { word: "Fondness", message: "Fondness is the warmth that lingers long after the moment has passed." },
    { word: "Infatuation", message: "'Infatuation is the spark that can light the fire of a lifetime.' — The Great Gatsby, F. Scott Fitzgerald" },
    { word: "Loyalty", message: "'Loyalty is love's steadfast companion, unwavering through time and trial.' — The Count of Monte Cristo, Alexandre Dumas" },
    { word: "Ardor", message: "Ardor is the fiery passion that fuels the journey of love." },
    { word: "Affinity", message: "'Affinity is the invisible thread that draws two souls together.' — The Alchemist, Paulo Coelho" },
    { word: "Romantic", message: "'Romantic love is the poetry written on the heart's pages.' — The Notebook, Nicholas Sparks" },
    { word: "Sincerity", message: "Sincerity is the honest voice of love, speaking without fear or pretense." },
    { word: "Attraction", message: "'Attraction is the magnetism that pulls hearts closer together.' — Romeo and Juliet, William Shakespeare" },
    { word: "Companionship", message: "Companionship is the quiet joy of walking through life hand in hand." },
    { word: "Empathy", message: "'Empathy is the bridge that connects hearts, allowing love to flow freely.' — The Book Thief, Markus Zusak" },
    { word: "Kindness", message: "'Kindness is love in action, a gentle touch on the world's wounds.' — To Kill a Mockingbird, Harper Lee" },
    { word: "Respect", message: "Respect is the foundation that allows love to grow strong and true." },
    { word: "Support", message: "'Support is the hand that lifts you up when the world tries to pull you down.' — The Help, Kathryn Stockett" },
    { word: "Understanding", message: "Understanding is the light that banishes the shadows of misunderstanding." },
    { word: "Patience", message: "'Patience is love's quiet strength, waiting without complaint.' — Jane Eyre, Charlotte Brontë" },
    { word: "Compassion", message: "Compassion is the heart's response to the pain of others, wrapped in kindness." },
    { word: "Encouragement", message: "'Encouragement is the voice of love, whispering 'you can' when the world says 'you can't.'' — Wonder, R.J. Palacio" },
    { word: "Gratitude", message: "Gratitude is the echo of love, thanking the universe for the gift of each other." },
    { word: "Hopefulness", message: "'Hopefulness is the dawn that follows the darkest night of the soul.' — The Hobbit, J.R.R. Tolkien" },
    { word: "Contentment", message: "Contentment is the peace that comes from loving and being loved in return." },
    { word: "Joyfulness", message: "'Joyfulness is the song of the heart when love fills its every corner.' — Anne of Green Gables, L.M. Montgomery" },
    { word: "Reassurance", message: "Reassurance is the gentle reminder that you are not alone, and never will be." },
    { word: "Solace", message: "'Solace is the comfort found in the arms of the one who loves you unconditionally.' — The Fault in Our Stars, John Green" },
    { word: "Tranquility", message: "Tranquility is the calm that comes from knowing you are loved beyond measure." },
    { word: "Warmth", message: "'Warmth is the glow of love, lighting up even the coldest of days.' — Little Women, Louisa May Alcott" },
    { word: "Acceptance", message: "Acceptance is the embrace that says, 'I love you as you are.'" },
    { word: "Admiration", message: "'Admiration is the spark that ignites the flame of love.' — Pride and Prejudice, Jane Austen" },
    { word: "Affectionate", message: "Affectionate love is the tender touch that heals and comforts." },
    { word: "Amity", message: "'Amity is the peaceful bond that unites hearts in harmony.' — The Giver, Lois Lowry" },
    { word: "Bond", message: "A bond is the unbreakable tie that connects hearts across time and distance." },
    { word: "Charity", message: "'Charity is love in its purest form, given freely and without expectation.' — Les Misérables, Victor Hugo" },
    { word: "Closeness", message: "Closeness is the sweet comfort of knowing you are never alone." },
    { word: "Comforting", message: "'Comforting love is the shelter that guards against life's storms.' — The Secret Garden, Frances Hodgson Burnett" },
    { word: "Connection", message: "Connection is the invisible thread that binds hearts together." },
    { word: "Delight", message: "'Delight is the laughter that bubbles up when love fills your heart.' — Emma, Jane Austen" },
    { word: "Endearing", message: "'Endearing love is the sweetness that lingers in every memory.' — Winnie-the-Pooh, A.A. Milne" },
    { word: "Fond", message: "Fond love is the warmth that wraps around you like a favorite blanket." },
    { word: "Gentle", message: "'Gentle love is the soft touch that heals and soothes the soul.' — The Velveteen Rabbit, Margery Williams" },
    { word: "Harmony", message: "Harmony is the melody that hearts create when they beat as one." },
    { word: "Inspiration", message: "'Inspiration is the spark that love ignites in the darkest of times.' — The Alchemist, Paulo Coelho" },
    { word: "Kindred", message: "Kindred spirits are the hearts that recognize each other across any distance." },
    { word: "Loyal", message: "'Loyal love is the anchor that holds fast in the stormiest seas.' — The Odyssey, Homer" },
    { word: "Nurturing", message: "Nurturing love is the care that helps hearts grow strong and true." },
    { word: "Reverence", message: "Reverence is the deep respect that honors the soul of the one you love." },
    { word: "Security", message: "'Security is the peace that comes from knowing you are loved unconditionally.' — The Little Prince, Antoine de Saint-Exupéry" },
    { word: "Sympathy", message: "Sympathy is the heart's echo, feeling with another in their joy and pain." },
    { word: "Trusting", message: "Trusting love is the courage to open your heart completely." },
    { word: "Unity", message: "'Unity is the strength found in standing together, heart to heart.' — The Four Agreements, Don Miguel Ruiz" },
    { word: "Strength", message: "Even on your hardest days, remember how far you've come. You have survived 100% of your worst days, and that's proof of your strength." },
    { word: "Resilience", message: "You are not defined by this moment. You are defined by how you rise after falling, how you keep going when it feels impossible." },
    { word: "Light", message: "'The sun will rise and we will try again.' — Twenty One Pilots. Even the darkest night will end, and the sun will rise." },
    { word: "Courage", message: "It takes courage to face another day when you're feeling low. You have that courage, even if you can't feel it right now." },
    { word: "Rest", message: "It's okay to rest. You don't have to be productive to be worthy. Sometimes the most important thing you can do is take care of yourself." },
    { word: "Growth", message: "'Rock bottom became the solid foundation on which I rebuilt my life.' — J.K. Rowling. Even the hardest days can be the start of something new." },
    { word: "Breathe", message: "When everything feels overwhelming, just breathe. One breath at a time, one moment at a time." },
    { word: "Perspective", message: "'This too shall pass.' — Ancient Persian adage. The pain you feel today won't always feel this intense." },
    { word: "Progress", message: "You may not see it now, but you're making progress. Every small step counts, even the ones that feel invisible." },
    { word: "Worth", message: "Your worth isn't determined by how you feel today. You are enough, exactly as you are, in this moment." },
    { word: "Healing", message: "'Healing takes time, and asking for help is a courageous step.' — Mariska Hargitay. Be patient with your healing journey." },
    { word: "Presence", message: "You don't have to fix everything right now. Just be present with yourself. That's enough for today." },
    { word: "Release", message: "It's okay to let go of what you can't control. Release the weight you're carrying—you don't have to hold it all." },
    { word: "Permission", message: "Give yourself permission to feel exactly as you do. Your feelings are valid, and they matter." },
    { word: "Lightness", message: "'Happiness can be found even in the darkest of times, if one only remembers to turn on the light.' — Albus Dumbledore" },
    { word: "Space", message: "It's okay to take up space. Your feelings, your needs, your existence—they all deserve space." },
    { word: "Grounded", message: "When everything feels overwhelming, focus on what grounds you—a deep breath, a familiar scent, the feeling of your feet on the floor." },
    { word: "Possibility", message: "This moment doesn't define your future. There is always the possibility of change, of better days ahead." },
    { word: "Voice", message: "Your voice matters. Your feelings matter. You are allowed to speak your truth, even if it's just to yourself." },
    { word: "Restoration", message: "Rest is not laziness. It is restoration. Give yourself the time and space to heal." },
    { word: "Gentleness", message: "Treat yourself with the same gentleness you would offer to someone you love who is hurting." },
    { word: "Faith", message: "Have faith in your ability to get through this. You have survived every hard day so far, and you will survive this one too." },
    { word: "Clarity", message: "You don't need to have all the answers right now. Clarity will come with time. For now, just be." },
    { word: "Refuge", message: "Create a small refuge for yourself today—a cozy corner, a favorite song, a comforting thought." },
    { word: "Purpose", message: "Even on days when it feels like nothing matters, remember that you do. Your presence in this world has purpose." },
    { word: "Calm", message: "'Peace. It does not mean to be in a place where there is no noise, trouble, or hard work. It means to be in the midst of those things and still be calm in your heart.' — Unknown" },
    { word: "Journey", message: "This is just one part of your journey. It doesn't define the whole story. Keep going, one step at a time." },
    { word: "Nurture", message: "Nurture yourself today. What is one small thing you can do to show yourself kindness?" },
    { word: "Belief", message: "Believe in your ability to get through this. You are stronger than you feel, braver than you believe." },
    { word: "Stillness", message: "In stillness, you can find peace. Take a moment to just be, without the need to fix or change anything." },
    { word: "Renewal", message: "Every morning is a chance to begin again. Today is a new day, a fresh start." },
    { word: "Safe", message: "You are safe in this moment. Even if everything feels uncertain, right now, you are here, and that is enough." },
    { word: "Brave", message: "It takes bravery to face another day when you're feeling low. You are braver than you know." },
    { word: "Peace", message: "'Do not let the behavior of others destroy your inner peace.' — Dalai Lama. Protect your peace today." },

    
    { word: "Fearless", message: "'You are my dearest punishment.' — Cardan to Jude, The Cruel Prince." },
    { word: "Fierce", message: "'I hate you because I could not make myself hate you.' — Cardan, The Wicked King." },
    { word: "Defiant", message: "'If I cannot be better than them, I will become so much worse.' — Jude, The Cruel Prince." },
    { word: "Surrender", message: "'You are my heart, my life, my entire existence.' — Cardan to Jude, The Queen of Nothing." },
    { word: "Vulnerable", message: "'I was afraid that I loved you so much that I would go mad.' — Cardan, The Wicked King." },
    { word: "Consume", message: "'Kiss me again. Kiss me until I am sick of it.' — Cardan, The Wicked King." },
    { word: "Unworthy", message: "'I thought of you every moment since you left. I tried not to, but I couldn't stop.' — Cardan, The Queen of Nothing." },
    { word: "Obsession", message: "'You are my weakness and my salvation both.' — Cardan to Jude." },
    { word: "Chaos", message: "'Perhaps I will keep you here until you love me.' — Cardan, The Queen of Nothing." },
    { word: "Torment", message: "'I love you in my most human moments, when I am at my worst.' — Cardan." },
    { word: "Redemption", message: "'I can be wicked still. For you.' — Cardan to Jude." },
    { word: "Inevitable", message: "'You were always going to be my ruin.' — Cardan, The Wicked King." },
    { word: "Conquer", message: "'I have to conquer the world because I cannot conquer you.' — Jude." },
    { word: "Betrayal", message: "'Even when I hated you, I loved you.' — Cardan to Jude." },
    { word: "Vengeance", message: "'Knowing I love you, does it hurt you more?' — Jude, The Cruel Prince." },
    { word: "Throne", message: "'I'd rather sit beside you on a throne than rule the world without you.' — Cardan." },
    { word: "Devotion", message: "'Let me be the first to say I love you, because I do.' — Cardan, The Queen of Nothing." },
    { word: "Wicked", message: "'You may be the High King, but I will always be wicked.' — Jude." },
    { word: "Ache", message: "'Being near you hurts. Being away from you hurts worse.' — Cardan to Jude." },
    { word: "Eternal", message: "'Forever is a long time, but I will spend it with you.' — Cardan, The Queen of Nothing." },
    { word: "Hate", message: "'“Most of all, I hate you because I think of you. Often. It's disgusting, and I can't stop.” Cardan, The Cruel Prince" },

    { word: "Darkness", message: "'To the stars who listen and the dreams that are answered.' — Rhysand, ACOMAF." },
    { word: "Salvation", message: "'I would have let the world burn to keep you safe.' — Rhysand to Feyre." },
    { word: "Wings", message: "'I love you without reservation, to every corner of my soul.' — Rhysand, ACOMAF." },
    { word: "Starlight", message: "'You are the light that chases away my darkness.' — Rhysand to Feyre. " },
    { word: "Mate", message: "'The bond between us is unbreakable.' — Rhysand, ACOWAR." },
    { word: "Worthy", message: "'You are worthy of everything good in this world.' — Rhysand to Feyre." },
    { word: "Freedom", message: "'I will not be a prisoner, not even to my own feelings.' — Feyre." },
    { word: "Rebirth", message: "'I was reborn the moment I met you.' — Rhysand to Feyre." },
    { word: "Night", message: "'Night found me in my darkest hour and showed me I could still shine.' — Feyre." },
    { word: "Court", message: "'My court is a place for dreamers.' — Rhysand." },
    { word: "Dreams", message: "'Dreams are the wings that carry us through the night.' — Rhysand, ACOMAF." },
    { word: "Fierce", message: "'I am no one's property. I am my own person.' — Feyre." },
    { word: "Immortal", message: "'I will love you for eternity and beyond.' — Rhysand." },
    { word: "Power", message: "'Power doesn't come from how hard you can hit, but from how much you can endure.' — Feyre." },
    { word: "Shield", message: "'I will be your shield against the darkness.' — Rhysand to Feyre." },
    { word: "Stars", message: "'We are made of starlight.' — Rhysand." },
    { word: "Survive", message: "'Surviving is not living.' — Feyre." },
    { word: "Velaris", message: "'This city of dreams is nothing compared to the dream of loving you.' — Rhysand." },
    { word: "Crown", message: "'No crown sits easy on any head.' — Rhysand." },
    { word: "Warrior", message: "'I am a warrior. I was made for battle, not sitting on the sidelines.' — Feyre." },
    
    { word: "Crows", message: "'No mourners, no funerals.' — Kaz, Six of Crows. We protect the ones we love." },
    { word: "Saints", message: "'I would come for you. And if I couldn't walk, I'd crawl to you.' — Kaz to Inej. Love knows no obstacles." },
    { word: "Gloves", message: "'I will have you without armor, or I will not have you at all.' — Inej to Kaz. Love requires vulnerability." },
    { word: "Wraith", message: "'She was a creature of darkness, and I loved her for it.' — Kaz about Inej. We love people for their entirety." },
    { word: "Knives", message: "'I am not weak. I am strong because of what I've survived.' — Inej. Your survival is your strength." },
    { word: "Harbor", message: "'You are my anchor in the storm.' — Kaz to Inej. Love keeps us grounded." },
    { word: "Barrel", message: "'The Barrel didn't break me. Nothing will.' — Inej. You are unbreakable." },
    { word: "Crow", message: "'When everyone else left, you stayed.' — Inej to Kaz. Loyalty is the truest form of love." },
    { word: "Touch", message: "'I will fight the demons in my mind to hold your hand.' — Kaz to Inej. Love is worth fighting for." },
    { word: "Freedom", message: "'I want you to be free, even if it means losing you.' — Kaz to Inej. True love wants the best for the other." },
    { word: "Spider", message: "'I am the spider that weaves her own web.' — Inej. Create your own destiny." },
    { word: "Miracle", message: "'Every moment with you is a miracle I didn't deserve.' — Kaz. Appreciate every moment together." },
    { word: "Ketterdam", message: "'This city tried to destroy us, but we survived.' — Inej. Together, we overcome anything." },
    { word: "Lock", message: "'There is no lock I cannot pick, no wall I cannot climb.' — Kaz. No obstacle is too great." },
    { word: "Ships", message: "'I will sail the world for you.' — Inej. Love takes us on great adventures." },
    { word: "Revenge", message: "'I will tear down the world for the ones I love.' — Kaz. Love inspires fierce protection." },
    { word: "Dregs", message: "'We are not disposable. We are irreplaceable.' — Inej. You are irreplaceable." },
    { word: "Silence", message: "'In the silence between heartbeats, I found you.' — Kaz to Inej. Love speaks in quiet moments." },
    { word: "Ghost", message: "'I was a ghost until you saw me.' — Inej to Kaz. Love helps us be seen." },
    { word: "Breathe", message: "'With you, I remember how to breathe.' — Kaz to Inej. Love gives us life." },
    
    { word: "Patroclus", message: "'He is half my soul, as the poets say.' — Achilles about Patroclus. Some souls are meant to be together." },
    { word: "Glory", message: "'I would choose you over glory any day.' — Achilles. Love is the greatest glory." },
    { word: "Phthia", message: "'In the summers, we were gods.' — Patroclus. Cherish the golden moments." },
    { word: "Lyre", message: "'His voice was the most beautiful thing I had ever heard.' — Patroclus about Achilles. Love finds beauty in everything." },
    { word: "Immortal", message: "'Name one hero who was happy.' — Patroclus. True happiness comes from love, not glory." },
    { word: "Troy", message: "'I will go anywhere with you.' — Patroclus. Love follows wherever it leads." },
    { word: "Golden", message: "'He was like the sun, and I was just a mortal basking in his light.' — Patroclus. Some loves illuminate our entire world." },
    { word: "Prophecy", message: "'I would defy the gods themselves for you.' — Achilles. Love transcends fate." },
    { word: "Beloved", message: "'You are my beloved, my most precious.' — Achilles to Patroclus. Tell them they are precious to you." },
    { word: "Together", message: "'In the darkness, we found each other.' — Patroclus. Love finds us even in the darkest times." },
    { word: "Hero", message: "'The heroes of old had nothing on the hero of my heart.' — Patroclus. The person you love is your hero." },
    { word: "Gentle", message: "'He was gentle with me when no one else was.' — Patroclus about Achilles. Gentleness is a form of love." },
    { word: "Mortal", message: "'Being mortal means I can love you now.' — Patroclus. Embrace the present moment." },
    { word: "Ashes", message: "'Let our ashes mix together for eternity.' — Achilles. Love endures beyond death." },
    { word: "Swift", message: "'Swift-footed Achilles, but his heart was always with me.' — Patroclus. No matter where you go, love follows." },
    { word: "Fate", message: "'I would choose this fate again and again if it meant loving you.' — Achilles. Love is worth any price." },
    { word: "Music", message: "'His music made even the stars jealous.' — Patroclus. Find the music in your love story." },
    { word: "Promise", message: "'I promised to protect you. I will keep that promise.' — Achilles. Keep your promises to those you love." },
    { word: "Sea", message: "'Like the sea, my love for you is endless.' — Patroclus. Let your love be boundless." },
    { word: "Memory", message: "'They will remember us.' — Patroclus. Your love story matters." },
    
    { word: "Pride", message: "'You have bewitched me, body and soul.' — Mr. Darcy to Elizabeth. Love transcends pride." },
    { word: "Prejudice", message: "'I was in the middle before I knew that I had begun.' — Mr. Darcy. Love catches us off guard." },
    { word: "Pemberley", message: "'I was wrong. I was blinded by my own prejudice.' — Elizabeth. Love opens our eyes." },
    { word: "Ardently", message: "'You must allow me to tell you how ardently I admire and love you.' — Mr. Darcy. Express your love boldly." },
    { word: "Tolerable", message: "'She is not handsome enough to tempt me.' became 'She is the handsomest woman of my acquaintance.' — Mr. Darcy. Love changes everything." },
    { word: "Stubborn", message: "'My good opinion once lost is lost forever.' But love proved otherwise. — Mr. Darcy. Love softens the hardest hearts." },
    { word: "Bennett", message: "'I am happier than I ever thought possible.' — Elizabeth. Love brings unexpected happiness." },
    { word: "Dancing", message: "'Every savage can dance.' — Mr. Darcy. But only the brave love openly." },
    { word: "Walk", message: "'I must learn to be content with being happier than I deserve.' — Elizabeth. You deserve all the love you receive." },
    { word: "Letters", message: "'His letter showed me the man I misjudged.' — Elizabeth. Take time to understand those you love." },
    { word: "Estate", message: "'I could have loved you had you behaved in a more gentlemanlike manner.' — Elizabeth. Love yourself enough to have standards." },
    { word: "Rain", message: "'I love you. Most ardently. Please do me the honor of accepting my hand.' — Mr. Darcy. Don't let the storms stop you from loving." },
    { word: "Sister", message: "'For the first time in my life, I am truly happy.' — Jane Bennet. Love brings us joy." },
    { word: "Eyes", message: "'Your eyes captured me before I knew your name.' — Mr. Darcy. Love at first sight exists." },
    { word: "Netherfield", message: "'Happiness in marriage is entirely a matter of chance.' — Charlotte. But true love is no accident." },
    
    { word: "Plain", message: "'I am no bird; and no net ensnares me.' — Jane Eyre. Your worth is not determined by your appearance." },
    { word: "Equal", message: "'I am your equal.' — Jane to Rochester. Love recognizes equality." },
    { word: "Soul", message: "'I have a thing in my breast that is divine.' — Jane Eyre. Your soul is divine and worthy of love." },
    { word: "Fire", message: "'I am no longer the girl I was. I have been through the fire.' — Jane. What you've survived has made you stronger." },
    { word: "Reader", message: "'Reader, I married him.' — Jane Eyre. Write your own happy ending." },
    { word: "Thornfield", message: "'Even through darkness, love finds a way.' — Jane Eyre. Trust that love will find you." },
    { word: "Mad", message: "'I would always rather be happy than dignified.' — Jane Eyre. Choose happiness over pride." },
    { word: "Return", message: "'I love you more than words can express.' — Rochester. Sometimes words fail, but love never does." },
    { word: "Strange", message: "'Do you think, because I am poor, obscure, plain, and little, I am soulless and heartless?' — Jane. Your circumstances do not define your worth." },
    { word: "Independent", message: "'I can live alone, if self-respect and circumstances require me to do so.' — Jane. Independence is strength." },
    { word: "Moor", message: "'I could not help loving him.' — Jane about Rochester. We cannot control who we love." },
    { word: "Voice", message: "'I heard his voice calling me across the miles.' — Jane. Love transcends distance." },
    { word: "Simple", message: "'Simple love is the most profound.' — Jane Eyre. Love doesn't need to be complicated." },
    { word: "Heart", message: "'My heart beats for you alone.' — Rochester to Jane. Give your heart to someone worthy." },
    { word: "Truth", message: "'I must speak the truth as I see it.' — Jane. Honesty is the foundation of love." },
    
    { word: "Circus", message: "'The circus arrives without warning.' — The Night Circus. Love often arrives unexpectedly." },
    { word: "Magic", message: "'You are magic itself.' — Marco to Celia. See the magic in those you love." },
    { word: "Stars", message: "'We are bound by stars and destiny.' — The Night Circus. Some connections are written in the stars." },
    { word: "Game", message: "'It is not a game, it is love.' — Celia. Love is more than a competition." },
    { word: "Tent", message: "'In this tent of wonders, I found you.' — Marco. Find wonder in your love." },
    { word: "Midnight", message: "'At midnight, all things are possible.' — The Night Circus. Believe in possibilities." },
    { word: "Dream", message: "'You are the dream I never knew I had.' — Marco to Celia. Love reveals dreams we didn't know we held." },
    { word: "Fire", message: "'Our love burns brighter than any flame.' — Celia. Let your love burn bright." },
    { word: "Time", message: "'Time bends around you.' — Marco to Celia. With love, time seems to stop." },
    { word: "Wonder", message: "'You are the greatest wonder in this circus.' — Marco. See the wonder in your beloved." },
    { word: "Eternal", message: "'We are eternal, you and I.' — Celia. Love can be eternal." },
    { word: "Black", message: "'In the black and white of this circus, you are my color.' — Marco. Love adds color to life." },
    { word: "White", message: "'Pure as snow, strong as steel.' — Celia. Love can be both gentle and strong." },
    { word: "Bonfire", message: "'We are the bonfire that never dies.' — The Night Circus. Keep the flame of love alive." },
    { word: "Reverie", message: "'Lost in the reverie of loving you.' — Marco. Let yourself be lost in love." },
    
    { word: "Heathcliff", message: "'He's more myself than I am. Whatever our souls are made of, his and mine are the same.' — Catherine. Soul connections are real." },
    { word: "Moors", message: "'My love for Heathcliff resembles the eternal rocks beneath.' — Catherine. Some loves are eternal and unshakeable." },
    { word: "Haunted", message: "'Haunt me, then. Be with me always.' — Heathcliff. Love transcends even death." },
    { word: "Wild", message: "'He's wild, but he's mine.' — Catherine about Heathcliff. Love accepts wildness." },
    { word: "Storm", message: "'Whatever our souls are made of, his and mine are the same.' — Catherine. Storm and calm, we are made of the same stuff." },
    { word: "Passion", message: "'I cannot live without my life! I cannot live without my soul!' — Heathcliff. Some passions are all-consuming." },
    { word: "Ghost", message: "'I cannot live without my soul.' — Heathcliff. Love becomes part of our very soul." },
    { word: "Window", message: "'Let me in through the window of your heart.' — Heathcliff. Open your heart to love." },
    { word: "Heath", message: "'Born of the heath, wild and free.' — Wuthering Heights. Love is wild and free." },
    { word: "Eternal", message: "'Our love is eternal as the moors.' — Catherine. Let your love be eternal." },
    
    { word: "Letters", message: "'I wrote you 365 letters. I wrote you every day for a year.' — Noah. Persistence in love shows devotion." },
    { word: "Summer", message: "'It was the summer that changed everything.' — The Notebook." },
    { word: "Boat", message: "'I see you rowing across the lake of my heart.' — Noah. Let love carry you." },
    { word: "House", message: "'I built this house for you.' — Noah. Love builds dreams into reality." },
    { word: "Rain", message: "'I chose you in the rain, and I choose you still.' — Noah to Allie. Choose love every day." },
    { word: "Remember", message: "'I remember everything about you.' — Noah. Cherish every memory." },
    { word: "Forever", message: "'We were together. I forget the rest.' — Walt Whitman, quoted in The Notebook." },
    { word: "Promise", message: "'It wasn't over. It still isn't over.' — Noah. Some love stories never end." },
    { word: "Dance", message: "'Dance with me until the end of time.' — The Notebook." },
    { word: "Alzheimer", message: "'Even when I forget, my heart remembers you.' — Allie. Love transcends memory." },
    
    { word: "Tomorrow", message: "Tomorrow is a new day with new possibilities. Hold on for just one more day." },
    { word: "Anchor", message: "When you feel like you're drowning, remember I am your anchor. You are not alone." },
    { word: "Rainbow", message: "After every storm comes a rainbow. Your rainbow is coming." },
    { word: "Phoenix", message: "Like the phoenix, you will rise from the ashes, stronger and more beautiful than before." },
    { word: "Bloom", message: "Even in the harshest winters, flowers find a way to bloom. So will you." },
    { word: "Mountain", message: "You have climbed mountains before. This one is no different. One step at a time." },
    { word: "Ocean", message: "Like the ocean, your feelings ebb and flow. The tide will change." },
    { word: "Butterfly", message: "A caterpillar must struggle to become a butterfly. Your struggle is your transformation." },
    { word: "Sunrise", message: "Every sunrise is proof that darkness never lasts forever." },
    { word: "Moonlight", message: "Even on the darkest nights, the moon provides light. Be your own moonlight." },
    { word: "Garden", message: "Tend to yourself like you would a garden. Water, sunlight, and patience." },
    { word: "River", message: "Like a river, keep flowing. Obstacles only make you stronger." },
    { word: "Stars", message: "Stars can't shine without darkness. Your struggles are revealing your light." },
    { word: "Tree", message: "A tree grows strongest when it weathers storms. You are growing stronger." },
    { word: "Wings", message: "You have wings. Sometimes you just need to remember how to use them." },
    { word: "Home", message: "You are your own home. Find comfort within yourself." },
    { word: "Treasure", message: "You are a treasure, more valuable than you know." },
    { word: "Spark", message: "Keep that spark alive. It's the seed of everything wonderful." },
    { word: "Melody", message: "Life is a melody. Even the sad notes create a beautiful song." },
    { word: "Canvas", message: "Your life is a canvas. You are the artist. Paint something beautiful." },
    { word: "Journey", message: "This is a journey, not a destination. Every step matters." },
    { word: "Warrior", message: "You are a warrior. Every day you fight is a victory." },
    { word: "Sunshine", message: "You are someone's sunshine. Don't let the clouds hide you." },
    { word: "Diamond", message: "Diamonds are formed under pressure. You are becoming a diamond." },
    { word: "Seed", message: "A seed must break open to grow. Your breaking is your beginning." },
    { word: "Bridge", message: "When you feel like you're burning bridges, remember you can build new ones." },
    { word: "Castle", message: "Build your castle of self-love. No one can tear it down." },
    { word: "Harbor", message: "Be your own safe harbor. Weather the storms within your walls." },
    { word: "Lighthouse", message: "Be the lighthouse that guides yourself through the fog." },
    { word: "Puzzle", message: "You are not broken. You are a puzzle becoming complete." },
    { word: "Storm", message: "You are not the storm. You are the calm after it." },
    { word: "Dawn", message: "Dawn always comes. The darkest hour is before the dawn." },
    { word: "Path", message: "There is no wrong path when you are learning and growing." },
    { word: "Feather", message: "Light as a feather, strong as steel. That's you." },
    { word: "Echo", message: "Your kindness echoes through the universe. Keep being kind." },
    { word: "Bloom", message: "Bloom where you are planted. Your roots are deep." },
    { word: "Wind", message: "The wind may bend you, but it will never break you." },
    { word: "Rain", message: "Let the rain wash away your worries. Tomorrow will be clearer." },
    { word: "Forest", message: "You are a forest, not just a tree. You contain multitudes." },
    { word: "Flame", message: "Keep your flame burning. It lights the way for others." },
    
    { word: "Narnia", message: "'Courage, dear heart.' — C.S. Lewis, The Voyage of the Dawn Treader. Take courage." },
    { word: "Hobbit", message: "'There is some good in this world, and it's worth fighting for.' — J.R.R. Tolkien. Keep fighting." },
    { word: "Potter", message: "'Happiness can be found even in the darkest of times.' — Albus Dumbledore. Find your happiness." },
    { word: "Wizard", message: "'It does not do to dwell on dreams and forget to live.' — Albus Dumbledore. Live in the present." },
    { word: "Gandalf", message: "'All we have to decide is what to do with the time that is given us.' — Gandalf. Use your time wisely." },
    { word: "Frodo", message: "'Even the smallest person can change the course of the future.' — Galadriel. You matter." },
    { word: "Aslan", message: "'Things never happen the same way twice.' — C.S. Lewis. Every day is a new opportunity." },
    { word: "Hermione", message: "'Books! And cleverness! There are more important things—friendship and bravery.' — Hermione." },
    { word: "Dobby", message: "'Dobby is free!' — Harry Potter. You have the power to free yourself." },
    { word: "Luna", message: "'Things we lose have a way of coming back to us in the end.' — Luna Lovegood." },
    { word: "Snape", message: "'Always.' — Severus Snape. Love endures through everything." },
    { word: "Phoenix", message: "'I need to be able to know the difference between what matters and what doesn't.' — Dumbledore." },
    { word: "Patronus", message: "'Think of the happiest memory you can.' — Harry Potter." },
    { word: "Marauder", message: "'Mischief managed.' — Harry Potter. You've got this handled." },
    { word: "Elderflower", message: "'The ones that love us never really leave us.' — Sirius Black." },
    { word: "Mirror", message: "'It does not do to dwell on dreams and forget to live.' — Dumbledore." },
    { word: "Quidditch", message: "'It's not about the win, it's about the flight.' — Inspired by Harry Potter." },
    { word: "Platform", message: "'Platform 9¾ exists for those who believe.' — Harry Potter. Believe in magic." },
    { word: "Wand", message: "'The wand chooses the wizard.' — Ollivander. Trust that you are chosen for your path." },
    { word: "Cloak", message: "'Invisibility cannot hide your worth.' — Inspired by Harry Potter." },
    
    { word: "Kindred", message: "'Kindred spirits are not so scarce as I used to think.' — Anne of Green Gables." },
    { word: "Bosom", message: "'A bosom friend - an intimate friend, you know - a really kindred spirit.' — Anne of Green Gables." },
    { word: "Tomorrow", message: "'Tomorrow is always fresh, with no mistakes in it yet.' — Anne of Green Gables." },
    { word: "Scope", message: "'There's such a lot of different Annes in me.' — Anne of Green Gables." },
    { word: "Gilbert", message: "'I don't want diamond sunbursts or marble halls. I just want you.' — Anne of Green Gables." },
    { word: "Cricket", message: "'To live will be an awfully big adventure.' — Peter Pan." },
    { word: "Fairy", message: "'Every time a child says, I don't believe in fairies, there is a fairy somewhere that falls down dead.' — Peter Pan." },
    { word: "Neverland", message: "'Second star to the right and straight on till morning.' — Peter Pan." },
    { word: "Wendy", message: "'You know that place between sleep and awake? That's where I'll always love you.' — Peter Pan." },
    { word: "Lost", message: "'All children, except one, grow up.' — Peter Pan." },
    { word: "Velvet", message: "'Real isn't how you are made. It's a thing that happens to you.' — The Velveteen Rabbit." },
    { word: "Rabbit", message: "'When you are Real you don't mind being hurt.' — The Velveteen Rabbit." },
    { word: "Nursery", message: "'Generally, by the time you are Real, most of your hair has been loved off.' — The Velveteen Rabbit." },
    { word: "Skin", message: "'Once you are Real you can't become unreal again.' — The Velveteen Rabbit." },
    { word: "Eyes", message: "'He had Real beauty. He was loved.' — The Velveteen Rabbit." }
];

const backgrounds = [
    { class: 'galaxy-bg', url: 'linear-gradient(to bottom, #0f0c29, #302b63, #24243e)' },
    { class: 'nebula-bg', url: 'linear-gradient(to bottom, #4b6cb7, #182848)' },
    { class: 'night-bg', url: 'linear-gradient(to bottom, #0a0e2a, #1a1f3a)' },
    { class: 'cosmic-bg', url: 'linear-gradient(to bottom, #000428, #004e92)' },
    { class: 'twilight-bg', url: 'linear-gradient(to bottom, #1e3c72, #2a5298)' },
    { class: 'aurora-bg', url: 'linear-gradient(to bottom, #0f2027, #203a43, #2c5364)' },
    { class: 'mystic-bg', url: 'linear-gradient(to bottom, #2c3e50, #4ca1af)' },
    { class: 'void-bg', url: 'linear-gradient(to bottom, #111, #333)' },
    { class: 'dream-bg', url: 'linear-gradient(to bottom, #2980b9, #6dd5fa, #ffffff)' },
    { class: 'eternity-bg', url: 'linear-gradient(to bottom, #0f2027, #2c5364)' },
    { class: 'infinity-bg', url: 'linear-gradient(to bottom, #141e30, #243b55)' },
    { class: 'horizon-bg', url: 'linear-gradient(to bottom, #000000, #434343)' },
    { class: 'paradise-bg', url: 'linear-gradient(to bottom, #16222a, #3a6073)' },
    { class: 'ocean-bg', url: 'linear-gradient(to bottom, #005c97, #363795)' },
    { class: 'sunset-bg', url: 'linear-gradient(to bottom, #36d1dc, #5b86e5)' },
    { class: 'dawn-bg', url: 'linear-gradient(to bottom, #ff758c, #ff7eb3)' },
    { class: 'magic-bg', url: 'linear-gradient(to bottom, #5433ff, #20bdff, #a5fecb)' },
    { class: 'enchant-bg', url: 'linear-gradient(to bottom, #7b4397, #dc2430)' },
    { class: 'whisper-bg', url: 'linear-gradient(to bottom, #3a7bd5, #00d2ff)' },
    { class: 'echo-bg', url: 'linear-gradient(to bottom, #000000, #0f0c29)' },
    { class: 'radiance-bg', url: 'linear-gradient(to bottom, #f12711, #f5af19)' },
    { class: 'serenity-bg', url: 'linear-gradient(to bottom, #8e2de2, #4a00e0)' },
    { class: 'harmony-bg', url: 'linear-gradient(to bottom, #4facfe, #00f2fe)' },
    { class: 'tranquil-bg', url: 'linear-gradient(to bottom, #48cae4, #0077b6)' },
    { class: 'velvet-bg', url: 'linear-gradient(to bottom, #ad5389, #3c1053)' },
    { class: 'bliss-bg', url: 'linear-gradient(to bottom, #360033, #0b8793)' },
    { class: 'celestial-bg', url: 'linear-gradient(to bottom, #0c3483, #a2b6df, #6b8cff, #a8c0ff)' },
    { class: 'luminous-bg', url: 'linear-gradient(to bottom, #654ea3, #eaafc8)' },
    { class: 'ethereal-bg', url: 'linear-gradient(to bottom, #108dc7, #ef8e38)' },
    { class: 'mystique-bg', url: 'linear-gradient(to bottom, #2b5876, #4e4376)' },
    { class: 'aurora-boreal-bg', url: 'linear-gradient(to bottom, #000428, #004e92)' }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { allLoveWords, backgrounds };
}
